
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Veyse
 */
public class FileChooserColorChooser extends javax.swing.JFrame {

    /**
     * Creates new form FileChooserColorChooserı
     */
    public FileChooserColorChooser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dosya_sec = new javax.swing.JButton();
        renk_degistir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        yazi_alani = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dosya_sec.setText("Dosya Seç");
        dosya_sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosya_secActionPerformed(evt);
            }
        });

        renk_degistir.setText("Renk Degistir");
        renk_degistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renk_degistirActionPerformed(evt);
            }
        });

        yazi_alani.setColumns(20);
        yazi_alani.setRows(5);
        jScrollPane1.setViewportView(yazi_alani);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dosya_sec)
                        .addGap(41, 41, 41)
                        .addComponent(renk_degistir)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dosya_sec)
                    .addComponent(renk_degistir))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dosya_secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosya_secActionPerformed
        JFileChooser fc = new JFileChooser(); //dosya secimi icin gerekli metod
        
        int i = fc.showOpenDialog(this);     //diyalog kutusunu actik (ok cancel...)

        if(i == JFileChooser.APPROVE_OPTION ) //egerki dosya secip oka tikladiysa bu komut caliscak approve option ok dugmesine bastigini belittir
        {
            File file = fc.getSelectedFile();   //sectigimiz dosyai  file referansina atadik
            
            String icerik="";  
            try(Scanner  scanner =new Scanner(new BufferedReader(new FileReader(file)))){  //okuma islemi 
                while(scanner.hasNextLine()){   
                icerik += scanner.nextLine()+"\n";
         
                }
                yazi_alani.setText(icerik);
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(FileChooserColorChooser.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
            
    }//GEN-LAST:event_dosya_secActionPerformed

    private void renk_degistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renk_degistirActionPerformed
        
            Color color = JColorChooser.showDialog(this,"bir renk secin", Color.RED);
            yazi_alani.setForeground(color); //yazi alanimizin rengini degistircek 
    }//GEN-LAST:event_renk_degistirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileChooserColorChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileChooserColorChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileChooserColorChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileChooserColorChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileChooserColorChooser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dosya_sec;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton renk_degistir;
    private javax.swing.JTextArea yazi_alani;
    // End of variables declaration//GEN-END:variables
}
