
import java.util.LinkedHashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Veyse
 */
public class Combobox_ve_RadioButton extends javax.swing.JFrame {
    Set<String> diller = new LinkedHashSet<String>();
    /**
     * Creates new form Combobox_ve_RadioButton
     */
    public Combobox_ve_RadioButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        java_radio = new javax.swing.JRadioButton();
        pyhton_radio = new javax.swing.JRadioButton();
        c_radio = new javax.swing.JRadioButton();
        d_goster = new javax.swing.JButton();
        cb_diller = new javax.swing.JComboBox<>();
        goster2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("combobox ve radio butonlari");

        buttonGroup1.add(java_radio);
        java_radio.setText("Java");

        buttonGroup1.add(pyhton_radio);
        pyhton_radio.setText("Pyhton");

        buttonGroup1.add(c_radio);
        c_radio.setText("C");

        d_goster.setText("Goster");
        d_goster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_gosterActionPerformed(evt);
            }
        });

        cb_diller.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "Css", "C#", "Php", " ", " ", " " }));
        cb_diller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_dillerActionPerformed(evt);
            }
        });

        goster2.setText("Goster Combobox'ı");
        goster2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goster2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pyhton_radio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_goster)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(java_radio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_radio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(goster2)
                            .addComponent(cb_diller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(java_radio)
                    .addComponent(cb_diller, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pyhton_radio)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(c_radio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(goster2)))
                .addGap(33, 33, 33)
                .addComponent(d_goster)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    public void goster(){ // eger ki sadece  bir radio butonu secmek istiyorsak buton group kullancaz propatires gidip none ozelligini degistirip buton group 1'i kullancaz
    String message="Şu Diller Secildi : \n";
    
    for(String dil : diller){
    message+= dil+ "\n";
    }
        JOptionPane.showMessageDialog(this, message);
    } 
    private void d_gosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_gosterActionPerformed
    // TODO add your handling code here:
      if(java_radio.isSelected())
        {
        diller.add("Java");
        }
        else
        {
        diller.remove("Java");
        }
         if(pyhton_radio.isSelected())
        {
        diller.add("Pyhton");
        }
        else
        {
        diller.remove("Pyhton");
        }
          if(c_radio.isSelected())
        {
        diller.add("C");
        }
        else
        {
        diller.remove("C");
        }
         goster();
       
    }//GEN-LAST:event_d_gosterActionPerformed

    private void cb_dillerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_dillerActionPerformed
        // TODO add your handling code here:   
    }//GEN-LAST:event_cb_dillerActionPerformed

    private void goster2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goster2ActionPerformed
        // TODO add your handling code here:
            String message="Şu Dilleri Sectiniz : "+cb_diller.getSelectedItem();
            JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_goster2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Combobox_ve_RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Combobox_ve_RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Combobox_ve_RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Combobox_ve_RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Combobox_ve_RadioButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton c_radio;
    private javax.swing.JComboBox<String> cb_diller;
    private javax.swing.JButton d_goster;
    private javax.swing.JButton goster2;
    private javax.swing.JRadioButton java_radio;
    private javax.swing.JRadioButton pyhton_radio;
    // End of variables declaration//GEN-END:variables
}
