
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Veyse
 */
public class StokUygulamasi extends javax.swing.JFrame {

    /**
     * Creates new form StokUygulamasi
     */
    public StokUygulamasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        urun_alani = new javax.swing.JTextField();
        fiyat_alani = new javax.swing.JTextField();
        mesaj_alani = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        urun_tablo_alani = new javax.swing.JTable();
        kategori_alani = new javax.swing.JComboBox<>();
        ekle_butonu = new javax.swing.JButton();
        guncelle_butonu = new javax.swing.JButton();
        sil_butonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ürün İsmi : ");

        jLabel2.setText("Fiyat : ");

        jLabel3.setText("Kategori : ");

        mesaj_alani.setForeground(new java.awt.Color(153, 0, 0));

        urun_tablo_alani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ürün ismi ", "Kategori ", "Fiyat"
            }
        ));
        urun_tablo_alani.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urun_tablo_alaniMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(urun_tablo_alani);

        kategori_alani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yiyecek", "İçecek", "Giyim", "Elektronik", "Kütür&Sanat", " " }));
        kategori_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategori_alaniActionPerformed(evt);
            }
        });

        ekle_butonu.setText("Ekle");
        ekle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle_butonuActionPerformed(evt);
            }
        });

        guncelle_butonu.setText("Güncelle");
        guncelle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelle_butonuActionPerformed(evt);
            }
        });

        sil_butonu.setText("Sil");
        sil_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_butonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fiyat_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                                    .addGap(73, 73, 73)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(kategori_alani, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(urun_alani))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(mesaj_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sil_butonu)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ekle_butonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(guncelle_butonu, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urun_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ekle_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kategori_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fiyat_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guncelle_butonu))
                        .addGap(38, 38, 38)
                        .addComponent(mesaj_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sil_butonu))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kategori_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategori_alaniActionPerformed
        

    }//GEN-LAST:event_kategori_alaniActionPerformed

    private void ekle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle_butonuActionPerformed
        // TODO add your handling code here:
         mesaj_alani.setText("");   
         DefaultTableModel model = (DefaultTableModel) urun_tablo_alani.getModel(); //urun tablosu uzerinde islem yapabilmek icin default table model metodunu kullaniyoruz 
                                                                                     //ve bu referansi urun tablosuna alanindaki modeli refereans alarak islemlerizi gercekleştiriyoruz  .
         
         if(urun_alani.getText().trim().equals("")){  //trim bastaki ve sondaki bosluklari siliyor ve guncellenmis Stringi direkt almamizi sagliyor
             mesaj_alani.setText("Ürün ismi boş gecilmez !!!"); 
             
         }
         else 
         {   // modelin icine object arrayini vererek degerleri giriyoruz ve oıbject arrayi olusturyoruz 
             Object[] eklenceklistesi ={urun_alani.getText(),kategori_alani.getSelectedItem().toString(),fiyat_alani.getText()};
             
             model.addRow(eklenceklistesi);  //bu sekilde direkt object arrayini eklemis oluypruz 
         }
        
    }//GEN-LAST:event_ekle_butonuActionPerformed

    private void guncelle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelle_butonuActionPerformed
        mesaj_alani.setText("");
        
        DefaultTableModel model = (DefaultTableModel) urun_tablo_alani.getModel(); //guncellemk icin model referansini aliyoruz
        
        int secili_row = urun_tablo_alani.getSelectedRow();  // tablo alnaindan bir satir secmesini istiyouruz 
        
        if(secili_row == -1){          //secilen satir bos veya satir hic secilmediyse 
        
        if(urun_tablo_alani.getRowCount() == 0)         //egerki secilen satir bos ise
        {
        mesaj_alani.setText("Ürün tablosu şu an bos...");
        }
        else // egerki guncellencek bir urun secilmediyse 
        {
        mesaj_alani.setText("Lütfen güncellenecek bir ürün secin");
        }
            }
        else  //eger ki bos degilse ve bir satir secildiyse siradaki islem urunu guncellemek 
        {
        model.setValueAt(urun_alani.getText(),secili_row,0);  //urun ismi sutunu aliyoruz
        model.setValueAt(kategori_alani.getSelectedItem(), secili_row, 1); //sutunlari aliyoruz sirayla
        model.setValueAt(fiyat_alani.getText(), secili_row, 2);
        
        mesaj_alani.setText("Ürün basari ile Güncellendi");  
        }
    }//GEN-LAST:event_guncelle_butonuActionPerformed

    private void urun_tablo_alaniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urun_tablo_alaniMouseClicked
        DefaultTableModel model = (DefaultTableModel) urun_tablo_alani.getModel();
        
        int secili_row= urun_tablo_alani.getSelectedRow();
        
        urun_alani.setText(model.getValueAt(secili_row,0).toString());  
        fiyat_alani.setText(model.getValueAt(secili_row, 2).toString());
        kategori_alani.setSelectedItem(model.getValueAt(secili_row, 1).toString());

    }//GEN-LAST:event_urun_tablo_alaniMouseClicked

    private void sil_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_butonuActionPerformed
        DefaultTableModel model = (DefaultTableModel) urun_tablo_alani.getModel();
        
        int secili_row = urun_tablo_alani.getSelectedRow();

                if(secili_row ==-1) //tabloda satir secili mi yada bosm u onu kntrol eder
                {
                if(urun_tablo_alani.getRowCount() == 0) //tablodaki satir sayisina bakiliyor
                {
                mesaj_alani.setText("Ürün tablosu şu anda boş...");
                }
                else
                {
            mesaj_alani.setText("Lütfen silincek bir ürün secin...");
                }   
       
                }
                else{
                model.removeRow(secili_row); //secili atiri silme metodu
                mesaj_alani.setText("Secili ürün basari ile silindi... ");
                }
    }//GEN-LAST:event_sil_butonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StokUygulamasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ekle_butonu;
    private javax.swing.JTextField fiyat_alani;
    private javax.swing.JButton guncelle_butonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kategori_alani;
    private javax.swing.JLabel mesaj_alani;
    private javax.swing.JButton sil_butonu;
    private javax.swing.JTextField urun_alani;
    private javax.swing.JTable urun_tablo_alani;
    // End of variables declaration//GEN-END:variables
}
