
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Veyse
 */
public class Siparis_Uygulamasi extends javax.swing.JFrame {
    Map<String,Integer> siparisler = new HashMap<String, Integer>();
    /**
     * Creates new form Siparis_Uygulamasi
     */
    public Siparis_Uygulamasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        corba = new javax.swing.JCheckBox();
        salata = new javax.swing.JCheckBox();
        beyti = new javax.swing.JCheckBox();
        kofte = new javax.swing.JCheckBox();
        kizartma = new javax.swing.JCheckBox();
        siparis = new javax.swing.JButton();
        su = new javax.swing.JCheckBox();
        ayran = new javax.swing.JCheckBox();
        soda = new javax.swing.JCheckBox();
        kola = new javax.swing.JCheckBox();
        milkshake = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MENU");

        jLabel2.setText("İÇEÇEKLER: ");

        jLabel3.setText("YİYECEKLER : ");

        corba.setText("Çorba - 12 TL");

        salata.setText("Salata - 15 TL");

        beyti.setText("Beyti - 60 TL");

        kofte.setText("Köfte - 50 TL");

        kizartma.setText("Kızartma 40 TL");

        siparis.setText("Siparis Ver ");
        siparis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siparisActionPerformed(evt);
            }
        });

        su.setText("Su - 3 TL");

        ayran.setText("Ayran - 5 TL ");

        soda.setText("Soda - 8 TL");

        kola.setText("Kola - 12 TL");

        milkshake.setText("Milkshake - 30 TL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(309, 309, 309))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(beyti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(corba, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(salata, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(kofte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kizartma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ayran, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                .addComponent(su, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(soda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(milkshake))
                        .addGap(257, 257, 257))))
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(siparis, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corba)
                    .addComponent(su))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salata)
                    .addComponent(ayran))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beyti)
                    .addComponent(soda))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kofte)
                    .addComponent(kola))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kizartma)
                    .addComponent(milkshake))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(siparis)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public void siparisleriGoster(){
            String message="";
            int tutar=0;
            if(siparisler.isEmpty())
            {
            message="Siparişiniz bulunmamaktadir ... ";
            }   
            else 
            { //mapte foreach donsuusu kullanilmiyorud bu yuzden entry set olusturcaz 
                message+="Sİparisleriniz : \n";
                for(Map.Entry<String,Integer> entry  : siparisler.entrySet()){
                    message += entry.getKey() + "\n";
                    tutar += entry.getValue();
            
            }
                message+="Toplam Siparis Tutarı : "+tutar;
            }
            JOptionPane.showMessageDialog(this, message);
                }
    private void siparisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siparisActionPerformed
        // TODO add your handling code here:
        
        if(ayran.isSelected())
        {
        siparisler.put("Ayran", 5);
        }
        else 
        {
        siparisler.remove("Ayran");
        }
        
        if(su.isSelected())
        {
        siparisler.put("Su", 3);
        }
        else 
        {
        siparisler.remove("Su");
        }
        
        if(soda.isSelected())
        {
        siparisler.put("Soda", 8);   
        }
        else 
        {
        siparisler.remove("Soda");
        }
        
        if(kola.isSelected())
        {
        siparisler.put("Kola", 12); 
        }
        else 
        {
        siparisler.remove("Kola");
        }
        
        if(milkshake.isSelected())
        {
        siparisler.put("Milkshake", 30);
        }
        else 
        {
        siparisler.remove("Milkshake");
        }
        
        if(corba.isSelected())
        {
        siparisler.put("Çorba", 12);
        }
        else 
        {
        siparisler.remove("Çorba");
        }
        
        if(salata.isSelected())
        {
        siparisler.put("Salata", 15);
        }
        else 
        {
        siparisler.remove("Salata");
        }
        
        if(beyti.isSelected())
        {
        siparisler.put("Beyti", 60);
        }
        else 
        {
        siparisler.remove("Beyti");
        }
        
        if(kofte.isSelected())
        {
        siparisler.put("Köfte",50);
        }
        else 
        {
        siparisler.remove("Köfte");
        }
        
        if(kizartma.isSelected())
        {
        siparisler.put("Kizartma",40);
        }
        else 
        {
        siparisler.remove("Kizartma");
        }
        
        siparisleriGoster();
      //  System.exit(0); //hem programi hemde gelen ekrani kapatiyor
        
    }//GEN-LAST:event_siparisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Siparis_Uygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Siparis_Uygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Siparis_Uygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Siparis_Uygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Siparis_Uygulamasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ayran;
    private javax.swing.JCheckBox beyti;
    private javax.swing.JCheckBox corba;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox kizartma;
    private javax.swing.JCheckBox kofte;
    private javax.swing.JCheckBox kola;
    private javax.swing.JCheckBox milkshake;
    private javax.swing.JCheckBox salata;
    private javax.swing.JButton siparis;
    private javax.swing.JCheckBox soda;
    private javax.swing.JCheckBox su;
    // End of variables declaration//GEN-END:variables
}
